[version]
path = "src/energyscope/__init__.py"

[build.targets.sdist]
packages = ["src/energyscope"]
exclude = ["tests"]
artifacts = [
    "*.csv",
    "*.mod",
    "*.dat",
]

[build.targets.wheel]
packages = ["src/energyscope"]
exclude = ["tests"]
artifacts = [
    "*.csv",
    "*.mod",
    "*.dat",
]

[envs.default.env-vars]
PIP_EXTRA_INDEX_URL = "https://pypi.ampl.com"

[env]
requires = [
    "hatch-mkdocs",
]

[env.collectors.mkdocs.docs]
path = "mkdocs.yml"

[envs.docs]
detached = false
dependencies = [
    "black",
    "openpyxl",
    "bibdatamanagement>=1.0.4",
    "pybtex",
    "pylatexenc",
    "tabulate",
]
[envs.docs.scripts]
deploy_version = "mike deploy -u -b docs $MIKE_VERSION latest"
deploy_main = "mike deploy -b docs main"

[envs.test]
dependencies = [
    "coverage[toml]",
    "pytest",
    "pytest-cov",
    "pytest-mock",
]
[envs.test.scripts]
run-coverage = "pytest --cov-config=pyproject.toml --cov=pkg --cov=tests"
run = "run-coverage --no-cov"

[envs.symposium]
dependencies = [
    "streamlit",
    "watchdog",
]
[envs.symposium.scripts]
streamlit = "python -m streamlit run examples/symposium20241003/symposium_streamlit.py"
